# Site settings
title:          Hmpark's notes
description:    "middlewre(WEB, WAS), Linux, Docker, k8s, Container, DevOps"
url:            "https://hongminpark.github.io"

# Author
author:
  name:         Hongmin Park
  url:          https://hongminpark.github.io
  email:        zhdals1026@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
